---
title: "Predictions"
author: "Matthew J Cashman"
date: "October 11, 2018"
output: html_document

---

#Visualize Data

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = getwd())
```

```{r Import and merge off previous script, warning=FALSE}
root.dir = getwd()
source(paste0(root.dir,"/import_merge_gis_field.R"))
```

```{r}
tile_ws_site %>%
  ggplot(aes(x=elev_above_thalweg,y=deposit_mm_yr))+
  geom_point()+
  facet_wrap(~strahler)
```

```{r}
fit<- lm(data=tile_ws_site[,c(-1:-4,-11,-16,-17)], log(deposit_mm_yr+1)~.)
summary(fit)
fit1<-step(fit, verbose=FALSE)
fit1$anova
summary(fit1)
```



#Join Watershed data for cleanup ----

##Getting mean values for each transect and taking the average for each site location
##Then, merging data based on watershed attributes for each Site

```{r}
# XS_ws <- XS_Change %>%
#   group_by(Site,Transect,Class) %>%
#   summarise_at(c("scour.rate","fill.rate","net.rate"), mean) %>%
#   inner_join(watershed_attr, by = c("Site"))
```

<!-- #Linear model Tree -->

<!-- lmdata <- XS_ws %>% -->
<!--   select(-Id,-Transect.y,-gridcode,-S100MIN,-S25MIN,-Rowid_, -SUM:-GRIDCODE_2) %>% -->
<!--   filter(Class == "Bank")  -->
<!-- lmdata$area_can <- as.numeric(lmdata$area_can) -->
<!-- lmdata$area_imper <- as.numeric(lmdata$area_imper) -->
<!-- lmdata$area_imper <- as.numeric(lmdata$area_imper) -->


<!-- XS_ws %>% -->
<!--   gather(key = variable, value = value, scour.rate, fill.rate, net.rate) %>%  -->
<!--   ggplot(aes(x=as.factor(Strahler), y=value, color=(Class), fill = Class))+ -->
<!--     geom_violin()+ -->
<!--   facet_grid(Class~variable) -->

<!-- lmfit<-lm(log(net.rate+2)~contr_area+Strahler+sum(pcent_imp+p_dev_med+p_dev_lo+p_dev_os), data=lmdata[,c(-1:-5)]) -->
<!-- summary(lmfit) -->


<!-- lmfit<-lm(log(net.rate+5)~., data=lmdata[,c(-1:-5)]) -->
<!-- lmfit -->
<!-- summary(lmfit) -->
<!-- stepfit<-step(lmfit) -->
<!-- summary(stepfit) -->

<!-- #PCA and PCR regressions  -->
<!-- require(pls) -->
<!-- library(tidyverse) -->
<!-- library(broom) -->
<!-- library(knitr) -->
<!-- library(ggfortify) -->

<!-- set.seed (1000) -->

<!-- lmdata_pca <- lmdata[,-2:-3] %>%  -->
<!--   nest() %>%  -->
<!--   mutate(pca = map(data, ~ prcomp(.x %>% select(-Site),  -->
<!--                                   center = TRUE, scale = TRUE)), -->
<!--          pca_aug = map2(pca, data, ~augment(.x, data = .y))) -->
<!-- lmdata_pca -->

<!-- var_exp <- lmdata_pca %>%  -->
<!--   unnest(pca_aug) %>%  -->
<!--   summarize_at(.vars = vars(contains("fittedPC")), .funs = funs(var)) %>%  -->
<!--   gather(key = pc, value = variance) %>%  -->
<!--   mutate(var_exp = variance/sum(variance), -->
<!--          cum_var_exp = cumsum(var_exp), -->
<!--          pc = str_replace(pc, ".fitted", "")) -->
<!-- var_exp -->

<!-- PCoI <- paste0("PC", 1:10) -->

<!-- var_exp %>%  -->
<!--   rename( -->
<!--     `Variance Explained` = var_exp, -->
<!--     `Cumulative Variance Explained` = cum_var_exp) %>% -->
<!--   gather(key = key, value = value, `Variance Explained`:`Cumulative Variance Explained`) %>%  -->
<!--   filter(pc %in% PCoI) %>% -->
<!--   ggplot(aes(pc, value, group = key)) +  -->
<!--   geom_point() +  -->
<!--   geom_line() +  -->
<!--   facet_wrap(~key, scales = "free_y") + -->
<!--   theme_bw() + -->
<!--   lims(y = c(0, 1)) + -->
<!--   labs(y = "Variance", -->
<!--        title = "Variance explained by each principal component") -->

<!-- lmdata_pca %>% -->
<!--   mutate( -->
<!--     pca_graph = map2( -->
<!--       .x = pca, -->
<!--       .y = data, -->
<!--       ~ autoplot(.x, loadings = TRUE, loadings.label = TRUE, -->
<!--                  loadings.label.repel = TRUE, -->
<!--                  data = .y, label = TRUE, -->
<!--                  label.label = "Site", -->
<!--                  label.repel = TRUE) + -->
<!--         theme_bw() + -->
<!--         labs(x = "Principal Component 1", -->
<!--              y = "Principal Component 2", -->
<!--              title = "First two principal components of PCA") -->
<!--     ) -->
<!--   ) %>% -->
<!--   pull(pca_graph) -->


<!-- if (!require('pacman')) install.packages('pacman'); library('pacman') -->

<!-- gbmdata <- lmdata %>% -->
<!--   ungroup() %>% -->
<!--   filter(Class=="Bank") %>% -->
<!--   select(-Transect.x:-fill.rate,-Strahler,-Shreve)  -->

<!-- #Transformations -->
<!-- p_load(caret) -->
<!-- nearZeroVar(gbmdata[,-1]) # -->

<!-- correlations <- cor(gbmdata[,-1]) -->
<!-- correlations -->

<!-- p_load(corrplot) -->
<!-- corrplot(correlations, order = "hclust") #Indetify clusters of similar variables -->

<!-- highCorr <- findCorrelation(correlations, cutoff = 0.75) -->
<!-- length(highCorr) -->
<!-- head(highCorr) -->

<!-- trans<-preProcess(gbmdata[1,], method = c("BoxCox", "center", "scale", "pca")) -->
<!-- trans -->

<!-- head(gbmdata$net.rate+1) -->
<!-- predict(NetTrans,(gbmdata$net.rate+1)) -->